---
output:
  pdf_document: default

---

```{r, eval=FALSE, echo=FALSE}
reticulate::py_install("pandas")
```

```{r, eval=FALSE, echo=FALSE}
# install.packages("reticulate")
library(reticulate)
virtualenv_create("r-reticulate",
python = "/usr/local/bin/python3")
use_virtualenv("r-reticulate", required = TRUE)
reticulate::py_install("scipy")
reticulate::py_install("numpy")
reticulate::py_install("wquantiles")
reticulate::py_install("statsmodels")
reticulate::py_install("matplotlib")
```

```{r}
reticulate::py_install("seaborn")
```


```{r}
a <- c(1,2,3)
print(a)
```
```{python}
a = [1,2,3]
print(a)
```
```{python}
import pandas as pd
state = pd.read_csv("state.csv")
print(state.head(8))
```
# zad1
```{r}
car_data <- read.csv("car.data", header = FALSE)
colnames(car_data) <- c("buying", "maint", "doors", "persons", "lug_boot", "safety", "class")
head(car_data)
```

```{python}
import pandas as pd
import matplotlib.pyplot as plt
```
```{python}

colnames = ["buying", "maint", "doors", "persons", "lug_boot", "safety", "class"]
car_data = pd.read_csv("car.data",names = colnames, header = None)
```


# zad2
```{r}
table(car_data$buying)
table(car_data$maint)
table(car_data$doors)
table(car_data$persons)
table(car_data$lug_boot)
table(car_data$safety)
table(car_data$class)
```

```{python}
car_data.buying.value_counts()
car_data["buying"].value_counts()
```




#zad3
```{r}
table(car_data$buying, car_data$class)
table(car_data$safety, car_data$class)
```

```{python}
pd.crosstab(car_data["buying"], car_data["class"])
pd.crosstab(car_data["safety"], car_data["class"])
```


#zad4
```{r}
library("ggplot2")
```

```{r}
ggplot(car_data)+
  geom_bar(aes(x = buying, fill = class))
```

```{r}
car_data_buying <- data.frame(table(buying = car_data$buying))

ggplot(car_data_buying) +
  geom_col(aes(x = buying, y = Freq))
```
```{python}
import seaborn as sns
```


```{python}
plt.figure()
sns.countplot(data = car_data, x = "buying", hue = "class")
plt.show()

plt.figure()
sns.histplot(data = car_data, x = "buying", hue = "class", multiple = "fill")
plt.show()
```



#zad 5
```{r}
table(car_data$safety, car_data$class)

```

```{python}
pd.crosstab(car_data["safety"], car_data["class"])
```
```{python}
car_data[car_data["class"] == "vgood"]["safety"].value_counts()
car_data[car_data["class"] == "vgood"]["safety"].value_counts().max()
car_data[car_data["class"] == "vgood"]["safety"].value_counts().idxmax()
```


```{r}
table(car_data$safety[car_data$class == "vgood"])
```
#zad 6
```{r}
table(car_data$buying, car_data$maint)
```

```{python}
pd.crosstab(car_data["buying"], car_data["maint"])
car_data[["buying", "maint"]].value_counts().sort_values()
```

