---
output:
  pdf_document: default
  html_document: default
---
```{r, echo = F, eval = F}
install.packages("reticulate")
```

```{r, echo = F, eval = F}
library("reticulate")
virtualenv_create("r-reticulate",
python = "/usr/local/bin/python3")
use_virtualenv("r-reticulate", required = TRUE)
```


# Zadanie 1 (R)

## 1. Czy przeżycie (`Survived`) zależało od płci (`Sex`)?

```{r}
titanic <- read.csv("Titanic.csv", sep = ",", header = TRUE)
head(titanic)
tabela <- xtabs(Freq ~ Survived + Sex, data = titanic)
tabela
```



```{r}
chisq.test(tabela)
```



```{r}
# (H0): Nie ma związku między płcią a szansą przeżycia.
# (H1): Istnieje zależność między płcią a przeżyciem.
#
# Wynik testu Chi-squared :
#
# Wartość statystyki wynosi 453.5 - jest to bardzo wysoka wartość 
#
# p-value = 2.2e-16 - jest to bardzo mała wielkość ,  
# dużo mniejsza od alphy = 0.05
#
# Z powyższych informacji wynika , że powinniśmy odrzucić (H0) na rzecz (H1),  
#czyli Istnieje silna zależność między płcią a przeżyciem.
```




# Zadanie 1 (Python)




```{r, echo = F, eval = F}
reticulate::py_install("scipy")
reticulate::py_install("numpy")
reticulate::py_install("wquantiles")
reticulate::py_install("statsmodels")
reticulate::py_install("matplotlib")
reticulate::py_install("pandas")
reticulate::py_install("seaborn")
```


```{python}
import seaborn as sns
import pandas as pd
from scipy.stats import chi2_contingency
```

```{python}
titanic = pd.read_csv("Titanic.csv")
```

```{python}
contingency = pd.pivot_table(titanic, values='Freq', index='Survived',  
columns='Sex', aggfunc='sum')
```

```{python}
chi2, p, dof, expected = chi2_contingency(contingency)
print(f"Chi2 = {chi2:.2f}, p = {p:.5f}")
```


# Zadanie 2 (R)

## 2. Czy przeżycie pasażerów zależało od klasy (`class`)?

```{r}
tabela_2 <- xtabs(Freq ~ Survived + Class, data = titanic)
tabela_2
chisq.test(tabela_2)
```

```{r}
# (H0): Klasa nie wpływa na szansę przeżycia.
# (H1): Istnieje zależność między klasą podróży a przeżyciem.
#
# Chi-Squared = 190.4 – bardzo wysoka wartość statystyki testowej.
# df = 3 – liczba stopni swobody.
# p-value < 2.2e-16 – dużo mniejsze niż aplha = 0.05.
#
# Z powyższych informacji wynika , że powinniśmy odrzucić (H0) na rzecz (H1),   
#czyli Istnieje silna zależność między klasą podróży a przeżyciem. Klasa,  
#w której podróżował pasażer, miała wpływ na jego szansę przeżycia katastrofy.
```

# Zadanie 2 (Python)

```{python}
contingency = pd.pivot_table(titanic, values='Freq', index='Survived',  
columns='Class', aggfunc='sum')
chi2, p, dof, expected = chi2_contingency(contingency)
print(f"Chi2 = {chi2:.2f}, p = {p:.5f}")
```

# Zadanie 3 (R)

## 3. Uzupełnij interpretację wyników z poprzednich zadań w oparciu o wyniki  uzyskane z funkcji prop.table() dostępnej w R.
  
```{r}
  
prop.table(tabela,2)
```

```{r}
#Przeżyło około 73% kobiet oraz tylko 21% mężczyzn
```



```{r}
prop.table(tabela_2, 2)
```
```{r}
# W 1. klasie przeżyło ponad 62% pasażerów.
# W 3. klasie – tylko około 24%.
# Wśród członków załogi – około 24% przeżyło.
# W 2. klasie – przeżyło około 41%
```

