---
title: "cw1"
output: html_document
date: "2025-03-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#zadania czesc 1

```{r}
(1+2^4)/((1/(2+sqrt(3)))-3)
```
```{r}
exp(10)
```

```{r}
(sqrt(2)-2^(1/4))/(2^(1/5)-2^(1/6))
```

```{r}
(pi/4) - atan(1)
```
```{r}
sin(pi/4)
```
```{r}
sin(45 * (pi/180))
```
```{r}
(1+(10/2025))^2025
```
```{r}
log(10, base = exp(1))
```
```{r}
log(10, base = 10)
```
```{r}
log(-10, base = exp(1))
```
```{r}
sqrt(-1)
```
```{r}
1/0
```

# zadania czesc 2


```{r}
my_name <- "Dawid Buler"
name_lenght <- nchar(my_name)
print(name_lenght)
now_doing <- paste(my_name,"programuje w R!")
print(toupper(now_doing))
```
# zadania czesc 3

```{r}
library(aplpack)
faces(1,face.type=2)

```

```{r}
library(aplpack)
apropos("test")
```
```{r}
library(effects)
print(TitanicSurvival)
summary(TitanicSurvival)
```
#czesc 4

```{r}
fav_1 <- 2
fav_2 <- 10
```

```{r}
print(fav_1 <- fav_1/sqrt(201))
print(fav_2 <- fav_2/sqrt(201))
```
```{r}
print(raw_sum <- sum(fav_1, fav_2))
```
```{r}
print(round_sum <- round(raw_sum, 1))
```
```{r}
print(round_1 <- round(fav_1,1))
print(round_2 <- round(fav_2,1))
```
```{r}
print(sum_round <- sum(round_1,round_2))
```
```{r}
max(round_sum, sum_round)
```

```{r}
add_three <- function(x){
  x + 3
}
```
```{r}
add_three(5)
```
```{r}
ten <- add_three(7)
```
```{r}
imperial_to_metric <- function(x,y){
  (((x * 12) + y) * 2.54) / 100 
}
imperial_to_metric(6,4)
```
```{r}
imperial_to_foot <- function(x){
((x * 100) / 2.54 ) / 12 
}
imperial_to_foot(1.93)
```
```{r}
pole_i_obwod <- function(r){
  return(c(pi*r^2, 2*pi*r))
}
pole_i_obwod(6.32)
```
```{r}
pole_i_obwod <- function(r){
  return(c(4*pi*r^2, (4/3)*pi*r^3))
}
pole_i_obwod(6.32)
```

```{r}
torus <- function(r, R) {
  if (r >= R) stop("r musi być mniejsze od R")

  pole <- 4 * pi^2 * R * r

  objetosc <- 2 * pi^2 * R * r^2
  
  return(list(pole = pole, objetosc = objetosc))
}
print(torus(7.33,22.54))
```





