```{r, eval=FALSE, echo=FALSE}
reticulate::py_install("pandas")
```

```{r, eval=FALSE, echo=FALSE}
install.packages("reticulate")
library(reticulate)
virtualenv_create("r-reticulate",
python = "/usr/local/bin/python3")
use_virtualenv("r-reticulate", required = TRUE)
reticulate::py_install("scipy")
reticulate::py_install("numpy")
reticulate::py_install("wquantiles")
reticulate::py_install("statsmodels")
reticulate::py_install("matplotlib")
reticulate::py_install("seaborn")
```

```{python}
import pandas as pd
```
```{python}
netflix.rating.isnull().sum()
```
```{python}
netflix = netflix.dropna(subset = ["rating","country"])
```

```{python}
netflix["type"].value_counts()
```

```{python}
import matplotlib.pyplot as plt
import seaborn as sns
```
```{python}
plt.figure()
(netflix["release_year"]).plot.hist()
plt.show()
```

```{python}
plt.figure()
sns.histplot(data = netflix, x = "release_year")
plt.show()
```



```{python}
df = netflix["rating"].value_counts()
df[df == df.max()]
```

